[env.collectors.datadog-checks]
check-types = true
mypy-args = [
    "--py2",
    "--follow-imports silent",
    "datadog_checks/dns_check",
    "--exclude '.*/config_models/.*\\.py$'",
]

[[envs.default.matrix]]
python = ["27", "38"]
